# frozen_string_literal: true

require 'sqlite3'
require 'fileutils'
require 'tempfile'
require_relative 'domain_filter'

# Hosts file generator
class HostsGenerator
  HEADER = <<~END_OF_WARNING
    # DO NOT EDIT THIS FILE
    # This file is automatically generated from nginx-proxy-manager
    # Any changes will be lost
    # generated by https://github.com/romkey/pdxhackerspace-hackstack-autogenerate-hosts
  END_OF_WARNING

  def initialize(config, logger)
    @config = config
    @logger = logger
    @domain_filter = DomainFilter.new(config.external_domain)
  end

  def generate
    @logger.info("Generating hosts file from database: #{@config.db_path}")

    hostnames = fetch_hostnames
    content = build_hosts_content(hostnames)
    write_atomic(content)

    @logger.info("dnsmasq configuration file generated successfully at #{@config.dnsmasq_path}")
    true
  rescue SQLite3::Exception => e
    @logger.error("Database error: #{e.message}")
    false
  rescue IOError, SystemCallError => e
    @logger.error("File write error: #{e.message}")
    false
  end

  # Exposed for testing
  def build_host_line(hostname)
    if hostname.include?('.')
      # External domain name - don't add additional suffixes
      "#{@config.ip_address} #{hostname}\n"
    else
      # Simple hostname - add all configured suffixes
      parts = [@config.ip_address, hostname, "#{hostname}.#{@config.domain_name}"]
      parts << "#{hostname}#{@config.local_suffix}" unless @config.local_suffix.empty?
      "#{parts.join(' ')}\n"
    end
  end

  private

  def fetch_hostnames
    db = SQLite3::Database.open(@config.db_path)
    rows = db.execute("SELECT domain_names FROM proxy_host WHERE is_deleted = 0")
    all_domains = @domain_filter.parse_from_rows(rows)
    @domain_filter.filter(all_domains)
  ensure
    db&.close
  end

  def build_hosts_content(hostnames)
    lines = [HEADER]

    hostnames.each do |hostname|
      lines << build_host_line(hostname)
    end

    lines.join
  end

  # Write to temp file then rename for atomic operation
  def write_atomic(content)
    dir = File.dirname(@config.dnsmasq_path)

    Tempfile.create('dnsmasq_hosts', dir) do |temp|
      temp.write(content)
      temp.flush
      temp.close
      FileUtils.mv(temp.path, @config.dnsmasq_path)
    end
  end
end

